version: '3.6'
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - mongodb_vol:/data/db
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - services-tier

  node:
    container_name: node
    restart: always
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - services-tier
    environment:
      - MIN_GOLOS_POWER
      - MAX_GOLOS_POWER
      - VOTE_BY_DAY_WITH_MAX_WEIGHT
      - LOGIN
      - WIF
      - DAY_START
      - BENEFICIARY_NAME
      - BENEFICIARY_PROCENT
      - MONGO_CONNECT_STRING
      - BLOCKCHAIN_SUBSCRIBE_TIMEOUT
      - BLOCKCHAIN_NODE_ADDRESS
      - METRICS_HOST
      - METRICS_PORT

volumes:
  mongodb_vol:           

networks:
  services-tier:
